### ISSUE TITLE
Problem with style escaping in inline HTML - Tailwindcss

### ISSUE THREAD

**Issue by enes-sahin** [yuanqing/create-figma-plugin#174]
### Describe the Bug

I encountered a problem with the style escaping in the inline HTML of the plugin's iframe when using `@create-figma-plugin` with tailwindcss. The issue seems to arise from the lack of escaping `\` characters in the generated inline style.

### Expected Behavior

The inline HTML style in the plugin's iframe should properly escape `\` characters, ensuring correct rendering of styles with class names that contain colons and other special characters.

### Actual Behavior

The inline HTML style lacks proper escaping of `\` characters, resulting in incorrect rendering of styles containing class names with colons.

### Code Example

```html
<!-- ui.tsx -->

...

<span className="dark:text-red-500">Hello</span>

...
```

```css
/* output.css */
...

@media (prefers-color-scheme: dark) {
  .dark\:text-red-500 {
    --tw-text-opacity: 1;
    color: rgb(239 68 68 / var(--tw-text-opacity));
  }
}



```

```html
<!-- HTML in figma console -->
...

#document
  <html class="figma-dark">
    
    ...

    <head>

      ...

      <style id="0e077b10a7">

        ...

        @media (prefers-color-scheme: dark) {
          .dark:text-red-500 {
            --tw-text-opacity: 1;
            color: rgb(239 68 68 / var(--tw-text-opacity));
          }
        }
      </style>

    </head>

    ...

  </html>

```
