### ISSUE TITLE
Global CSS import does not handle backslashes correctly

### ISSUE THREAD

**Issue by jsardev** [yuanqing/create-figma-plugin#209]
I wanted to use Tailwind CSS [arbitrary values](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values) and it did not work correctly with current `create-figma-plugin` implementation.

The problem is that Tailwind outputs properly escaped `[`/`]` signs in css, but it is not handled correctly in the inline import logic.

Consider this `output.css` file
```css
.grid-cols-\[1fr_1fr\] {
  grid-template-columns: 1fr 1fr;
}
```

After importing it via `import '!./output.css'` we get:
```css
.grid-cols-[1fr_1fr] {
  grid-template-columns: 1fr 1fr;
}
```

Which is incorrect CSS - the `[`/`]` values are considered atrribute selectors and not strings.

### Additional info

Version: `3.1.0`
